Update compatibility-chart.en.md (O2 Czech Republic, Pixel 6a)
kyujin-cho/pixel-volte-patch pull request #130
Opened 2023-05-12 11:37 UTC by soustruh

2023-05-19 09:32 UTC, teoren commented
Was about to create a similar pull request. ;-)
I can confirm the patch works in Czech Republic and O2 carrier, tested on my Pixel 6a with an eSIM.
Also works fine with Tesco Mobile (299) carrier with a physical SIM card. Both VoLTE and VoWiFi.

2023-05-21 07:11 UTC, kyujin-cho requested changes

2023-05-21 07:11 UTC, kyujin-cho commented on docs/compatibility-chart.en.md
> +| Europe        | Czech Republic (230)    | O2 (02)             | O                   | O                                       | Tested on my own Pixel 6a, both VoLTE & VoWiFi work |
Could you add a link which heads to this PR page as a reference?

2023-06-17 07:52 UTC, kyujin-cho approved these changes

2023-06-17 07:53 UTC, merged