Starting Shizuku without a PC(using wifi-debugging)
kyujin-cho/pixel-volte-patch pull request #43
Opened 2023-02-13 12:46 UTC by FarisZR

Hi!,
this is just a quick PR to add setting up Shizuku without needing a PC, I just tried it, and it worked.
It also makes re-applying the patch much easier.

2023-02-22 14:43 UTC, kyujin-cho requested changes

2023-02-22 14:43 UTC, kyujin-cho commented on README.en.md
>  5. Now continue to next section.
Splitting those two methods as a separate section seems much nicer.
```suggestion
### Starting Shizuku without PC (Wi-Fi connection required) 
1. Follow the [official guide to start Shizuku using Wifi debugging](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging) without needing any external PC, after that you should see something like "Shizuku is running" at your Pixel phone.
   ![image-4](https://github.com/kyujin-cho/pixel-volte-patch/raw/main/assets/Screenshot_20230206-035351.png)
2. Now continue to next section.

### Using a PC
1. Connect your Pixel phone with PC by following [this description](https://shizuku.rikka.app/guide/setup/#start-by-connecting-to-a-computer).
2. Start shizuku service by executing `adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh`. You should see something like "Shizuku is running" at your Pixel phone.
   ![image-3](https://github.com/kyujin-cho/pixel-volte-patch/raw/main/assets/Screenshot%202023-02-06%20at%203.54.00%20AM.png)
   ![image-4](https://github.com/kyujin-cho/pixel-volte-patch/raw/main/assets/Screenshot_20230206-035351.png)
3. Now continue to next section.
```

2023-02-25 23:06 UTC, FarisZR commented on README.en.md
>  5. Now continue to next section.
Done

2023-05-28 13:01 UTC, kyujin-cho approved these changes

2023-05-28 13:01 UTC, merged