Split VoLTE and VoWiFi checks and UI elements. Fixes #3.
kyujin-cho/pixel-volte-patch pull request #8
Opened 2023-02-07 19:28 UTC by victor-marino

PR that addresses issue #3. I renamed VoLTE-specific things (IMS -> VoLTE) so we can easily tell them apart from VoWiFi ones.

---

Please note:

I have removed the `KEY_CARRIER_AVAILABLE_VT_BOOL` setting for now, as it's not related to VoWiFi in any way. That's actually the setting for [ViLTE](https://www.gsma.com/futurenetworks/ip_services/vilte/), the Video over LTE feature that was standardised years ago by carriers (VT = [Video Telephony](https://developer.android.com/reference/android/telephony/CarrierConfigManager#KEY_CARRIER_VT_AVAILABLE_BOOL)).

Happy to add a third button for that if you want, although I'm not sure if carriers are actually using it nowadays.

2023-02-07 20:25 UTC, Kubis-Tomasz commented
@victor-marino Can you share builded apk so that I can test that without compilation on my side?

2023-02-08 01:29 UTC, kyujin-cho requested changes
Thanks for your contribution! Here's my initial code review.

2023-02-08 01:29 UTC, kyujin-cho commented on app/src/main/java/dev/bluehouse/enablevolte/MainActivity.kt
> +    var carrierVolteEnabled: Boolean,
To keep consistency across method and variable names, let's change Volte to VoLTE.
```suggestion
    var deviceVoLTEEnabled: Boolean,
    var carrierVoLTEEnabled: Boolean,
```

2023-02-08 01:29 UTC, kyujin-cho commented on app/src/main/java/dev/bluehouse/enablevolte/MainActivity.kt
> +    var carrierVowifiEnabled: Boolean,
Also here.
```suggestion
    var carrierVoWiFiEnabled: Boolean,
```

2023-02-08 01:29 UTC, kyujin-cho commented on app/src/main/java/dev/bluehouse/enablevolte/MainActivity.kt
> +    private fun updateVolteConfig(enableVolte: Boolean) {
Also here.
```suggestion
    private fun updateVolteConfig(enable VoLTE: Boolean) {
```

2023-02-08 10:14 UTC, kyujin-cho commented on app/src/main/java/dev/bluehouse/enablevolte/MainActivity.kt
> +    private fun updateVolteConfig(enableVolte: Boolean) {
<img width="613" alt="image" src="https://user-images.githubusercontent.com/2904494/217500734-20ebdb51-3117-4628-b39a-6d0d42f0d6a3.png">
Nevermind, let's just stick with `Volte` and `Vowifi`.

2023-02-08 10:14 UTC, kyujin-cho approved these changes

2023-02-08 10:15 UTC, merged

2023-02-09 00:06 UTC, luish77 commented
![Screenshot_20230208-200212](https://user-images.githubusercontent.com/124844783/217680074-f5eac2a6-fc27-49e2-8e2d-28d518e45825.png)
With this you could add the ability to show 4G+ or LTE+ icons. I would love to enable LTE+ icon instead of 4G+